UserIdParam:
  name: userId
  in: query
  description: id of the user(UUID) for whom to fetch activity logs
  schema:
    type: string
    format: uuid
    pattern: ^[0-9a-f]{8}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{12}$
AssetTypeParam:
  name: assetType
  in: query
  description: 'The type of asset to filter the activity logs. This parameter allows filtering by specific asset types.

    '
  required: false
  schema:
    type: string
    enum:
    - DATABANK
    - AI_MODEL
    - USECASE
SandboxTypeParam:
  name: sandboxType
  in: query
  description: 'Sandbox execution type used to filter audit logs. Possible values indicate the compute environment.

    '
  required: false
  schema:
    type: string
    enum:
    - cpu
    - gpu
AssetAccessPolicyParam:
  name: accessPolicy
  in: query
  description: 'The access policy of the asset to filter the activity logs. This parameter allows filtering by specific access
    policies such as `OPEN`, `RESTRICTED`, `PRIVATE`, `PII`.

    '
  required: false
  schema:
    type: string
    enum:
    - OPEN
    - RESTRICTED
    - PRIVATE
    - PII
RoleParam:
  name: role
  in: query
  description: 'This parameter allows filtering by specific role.

    '
  required: false
  schema:
    type: string
ActionParam:
  name: action
  in: query
  description: 'The type of action to filter the activity logs. This parameter allows filtering by specific action, such as
    `View`, `Download`, `Upload`, `Update`,`Delete` etc.

    '
  required: false
  schema:
    type: string
LogTypeParam:
  name: logType
  in: query
  description: 'The type of log to filter the activity logs. This parameter allows filtering by specific log types, such as
    `ASSET`, `USER_ACTION`, and `COMPUTE`.

    '
  required: false
  schema:
    type: string
OrganizationIdParam:
  name: orgId
  in: query
  description: 'The unique identifier (UUID) of the organization for which to fetch activity logs. Use this parameter to filter
    activity logs belonging to a specific organization.

    '
  schema:
    type: string
    format: uuid
    pattern: ^[0-9a-f]{8}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{4}\b-[0-9a-f]{12}$
PageParam:
  name: page
  in: query
  description: Page number for pagination
  required: false
  schema:
    type: integer
    default: 1
    minimum: 1
SizeParam:
  name: size
  in: query
  description: Page size for pagination
  required: false
  schema:
    type: integer
    default: 1000
    minimum: 1
SizeParamReport:
  name: size
  in: query
  description: Page size for pagination , used as limit for query request
  required: false
  schema:
    type: integer
    default: 1000
    minimum: 1
SortingParam:
  name: sort
  in: query
  description: 'This parameter allows sorting the results by up to 3 fields, separated by a semicolon (`;`). The format for
    each field is `fieldName:asc` or `fieldName:desc`. For example: `createdAt:desc;assetType:asc;userId:desc` will sort by
    creation date (descending), then asset type (ascending), then user ID (descending).'
  required: false
  schema:
    type: string
TimeParam:
  name: time
  in: query
  description: This parameter specifies the <b>start time</b> for the temporal-query in `ISO8601` format.
  schema:
    type: string
EndTimeParam:
  name: endtime
  in: query
  description: This parameter specifies the <b>endtime</b> for the temporal-query in `ISO8601` format.
  schema:
    type: string
TimeRelParam:
  name: timerel
  in: query
  description: 'The temporal relation type to be applied for the time filter. Must be one of: <b>between</b>, <b>before</b>,
    or <b>after</b>. <b>between</b> must be used with both `time` and `endtime`. <b>before</b> or <b>after</b> must be used
    with only `time`.

    '
  required: false
  schema:
    type: string
    enum:
    - between
    - before
    - after
OrgNameParam:
  name: name
  in: query
  description: 'The name of the organization sector to filter by.

    This parameter is used to filter entities based on their organizational sector.

    '
  required: false
  schema:
    type: string
EntityTypeParam:
  name: entity_type
  in: query
  description: The type of entity to filter by. This parameter is used to filter entities based on their type.
  required: false
  schema:
    type: string
OrgSectorParam:
  name: org_sector
  in: query
  description: The sector of the organization to filter by. This parameter is used to filter entities based on their organizational
    sector.
  required: false
  schema:
    type: string
StatusParam:
  name: status
  in: query
  description: The status of the asset request to filter by. This parameter is used to filter asset requests based on their
    status such as 'pending' , 'granted' and 'rejected'.
  required: false
  schema:
    type: string
